var searchData=
[
  ['calculatehistograms_0',['calculateHistograms',['../class_histogram.html#a42344cca1862f5427c5001010154862c',1,'Histogram::calculateHistograms()'],['../class_histogram.html#ab09251173022b398b0da4a347dc3bee6',1,'Histogram::calculateHistograms(Detail detail)'],['../histogram__kernel__intel_8cl.html#a4ac612743931723553216f836e6fd275',1,'calculateHistograms(global const int *pixels, global const int *numOfBins, global const int *format, global int *yAverageBins, global int *yVarianceBins, global int *uAverageBins, global int *uVarianceBins, global int *vAverageBins, global int *vVarianceBins, local int *yBlockSumAverage, local int *yBlockSumVariance, local int *uBlockSumAverage, local int *uBlockSumVariance, local int *vBlockSumAverage, local int *vBlockSumVariance):&#160;histogram_kernel_intel.cl'],['../histogram__kernel__nvidia_8cl.html#a75a12cf2f63a628b3da12e18aa3f4b6f',1,'calculateHistograms(global const int *pixels, global const int *numOfBins, global const int *format, global int *yAverageBins, global float *yVarianceBins, global int *uAverageBins, global float *uVarianceBins, global int *vAverageBins, global float *vVarianceBins, local int *yBlockSumAverage, local int *yBlockSumVariance, local int *uBlockSumAverage, local int *uBlockSumVariance, local int *vBlockSumAverage, local int *vBlockSumVariance):&#160;histogram_kernel_nvidia.cl']]],
  ['calculatehistogramssinglechannel_1',['calculateHistogramsSingleChannel',['../histogram__kernel__intel_8cl.html#a5f2c430a010534a85af2b3ebc4b529c5',1,'calculateHistogramsSingleChannel(global const int *pixels, global const int *numOfBins, global int *averageBins, global int *varianceBins, local int *blockSumAverage, local int *blockSumVariance):&#160;histogram_kernel_intel.cl'],['../histogram__kernel__nvidia_8cl.html#a9fe5f13af0a45c7132f48823d1452105',1,'calculateHistogramsSingleChannel(global const int *pixels, global const int *numOfBins, global int *averageBins, global float *varianceBins, local int *blockSumAverage, local int *blockSumVariance):&#160;histogram_kernel_nvidia.cl']]],
  ['calculatehistogramssinglechannelwithdetail_2',['calculateHistogramsSingleChannelWithDetail',['../histogram__kernel__intel_8cl.html#aebb0d407b9e53657534ee4e60f5592a7',1,'calculateHistogramsSingleChannelWithDetail(global const int *pixels, global const int *numOfBins, global float *average, global float *variance, global int *averageBins, global int *varianceBins, local int *blockSumAverage, local int *blockSumVariance):&#160;histogram_kernel_intel.cl'],['../histogram__kernel__nvidia_8cl.html#a79bc8aa58babf9e3d53ce27c0bdc2df0',1,'calculateHistogramsSingleChannelWithDetail(global const int *pixels, global const int *numOfBins, global float *average, global float *variance, global int *averageBins, global float *varianceBins, local int *blockSumAverage, local int *blockSumVariance):&#160;histogram_kernel_nvidia.cl']]],
  ['calculatehistogramswithdetail_3',['calculateHistogramsWithDetail',['../histogram__kernel__intel_8cl.html#a8c8ce69faef32b25be6dbe83075dc578',1,'calculateHistogramsWithDetail(global const int *pixels, global const int *numOfBins, global const int *format, global float *yAverage, global float *yVariance, global int *yAverageBins, global int *yVarianceBins, global float *uAverage, global float *uVariance, global int *uAverageBins, global int *uVarianceBins, global float *vAverage, global float *vVariance, global int *vAverageBins, global int *vVarianceBins, local int *yBlockSumAverage, local int *yBlockSumVariance, local int *uBlockSumAverage, local int *uBlockSumVariance, local int *vBlockSumAverage, local int *vBlockSumVariance):&#160;histogram_kernel_intel.cl'],['../histogram__kernel__nvidia_8cl.html#a3563b292231d35d5988d06b20ff66066',1,'calculateHistogramsWithDetail(global const int *pixels, global const int *numOfBins, global const int *format, global float *yAverage, global float *yVariance, global int *yAverageBins, global float *yVarianceBins, global float *uAverage, global float *uVariance, global int *uAverageBins, global float *uVarianceBins, global float *vAverage, global float *vVariance, global int *vAverageBins, global float *vVarianceBins, local int *yBlockSumAverage, local int *yBlockSumVariance, local int *uBlockSumAverage, local int *uBlockSumVariance, local int *vBlockSumAverage, local int *vBlockSumVariance):&#160;histogram_kernel_nvidia.cl']]],
  ['calculatesizes_4',['calculateSizes',['../class_histogram.html#add16bfb038983bcc3c15866debc15de4',1,'Histogram']]],
  ['channel_5',['Channel',['../class_histogram.html#a9321cc3ceee96efc42daf8f2a9dc6f15',1,'Histogram']]],
  ['color_6',['Color',['../class_histogram.html#a01abb40da9a8d34f6c5343226ddd1b03',1,'Histogram']]],
  ['createinputbuffers_7',['createInputBuffers',['../class_histogram.html#adedb2f8b31748e551715e5ea254650cb',1,'Histogram']]],
  ['createoutputbuffers_8',['createOutputBuffers',['../class_histogram.html#a2541f0894465ab70562aba105410c8e0',1,'Histogram']]],
  ['createoutputvectors_9',['createOutputVectors',['../class_histogram.html#aaf32593ad875581815ab059d1689ec7c',1,'Histogram']]]
];
